const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    location: "Malibu",
    country: "United States",
    geometry: { type: "Point", coordinates: [-118.7798, 34.0259] },
  },
  {
    title: "Modern Loft in Downtown",
    location: "New York City",
    country: "United States",
    geometry: { type: "Point", coordinates: [-74.0060, 40.7128] },
  },
  {
    title: "Mountain Retreat",
    location: "Aspen",
    country: "United States",
    geometry: { type: "Point", coordinates: [-106.8175, 39.1911] },
  },
  {
    title: "Historic Villa in Tuscany",
    location: "Florence",
    country: "Italy",
    geometry: { type: "Point", coordinates: [11.2558, 43.7696] },
  },
  {
    title: "Secluded Treehouse Getaway",
    location: "Portland",
    country: "United States",
    geometry: { type: "Point", coordinates: [-122.6765, 45.5152] },
  },
  {
    title: "Beachfront Paradise",
    location: "Cancun",
    country: "Mexico",
    geometry: { type: "Point", coordinates: [-86.8515, 21.1619] },
  },
  {
    title: "Rustic Cabin by the Lake",
    location: "Lake Tahoe",
    country: "United States",
    geometry: { type: "Point", coordinates: [-120.0324, 39.0968] },
  },
  {
    title: "Luxury Penthouse with City Views",
    location: "Los Angeles",
    country: "United States",
    geometry: { type: "Point", coordinates: [-118.2437, 34.0522] },
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    location: "Verbier",
    country: "Switzerland",
    geometry: { type: "Point", coordinates: [7.2266, 46.0960] },
  },
  {
    title: "Safari Lodge in the Serengeti",
    location: "Serengeti National Park",
    country: "Tanzania",
    geometry: { type: "Point", coordinates: [34.6857, -2.3333] },
  },
  {
    title: "Historic Canal House",
    location: "Amsterdam",
    country: "Netherlands",
    geometry: { type: "Point", coordinates: [4.9041, 52.3676] },
  },
  {
    title: "Private Island Retreat",
    location: "Fiji",
    country: "Fiji",
    geometry: { type: "Point", coordinates: [178.0650, -17.7134] },
  },
  {
    title: "Charming Cottage in the Cotswolds",
    location: "Cotswolds",
    country: "United Kingdom",
    geometry: { type: "Point", coordinates: [-1.8433, 51.8330] },
  },
  {
    title: "Historic Brownstone in Boston",
    location: "Boston",
    country: "United States",
    geometry: { type: "Point", coordinates: [-71.0589, 42.3601] },
  },
  {
    title: "Beachfront Bungalow in Bali",
    location: "Bali",
    country: "Indonesia",
    geometry: { type: "Point", coordinates: [115.1889, -8.4095] },
  },
  {
    title: "Mountain View Cabin in Banff",
    location: "Banff",
    country: "Canada",
    geometry: { type: "Point", coordinates: [-115.5708, 51.1784] },
  },
  {
    title: "Art Deco Apartment in Miami",
    location: "Miami",
    country: "United States",
    geometry: { type: "Point", coordinates: [-80.1918, 25.7617] },
  },
  {
    title: "Tropical Villa in Phuket",
    location: "Phuket",
    country: "Thailand",
    geometry: { type: "Point", coordinates: [98.3381, 7.8804] },
  },
  {
    title: "Historic Castle in Scotland",
    location: "Scottish Highlands",
    country: "United Kingdom",
    geometry: { type: "Point", coordinates: [-4.2026, 57.1200] },
  },
  {
    title: "Desert Oasis in Dubai",
    location: "Dubai",
    country: "United Arab Emirates",
    geometry: { type: "Point", coordinates: [55.2708, 25.2048] },
  },
  {
    title: "Rustic Log Cabin in Montana",
    location: "Montana",
    country: "United States",
    geometry: { type: "Point", coordinates: [-110.3626, 46.8797] },
  },
  {
    title: "Beachfront Villa in Greece",
    location: "Mykonos",
    country: "Greece",
    geometry: { type: "Point", coordinates: [25.3289, 37.4467] },
  },
  {
    title: "Eco-Friendly Treehouse Retreat",
    location: "Costa Rica",
    country: "Costa Rica",
    geometry: { type: "Point", coordinates: [-83.7534, 9.7489] },
  },
  {
    title: "Historic Cottage in Charleston",
    location: "Charleston",
    country: "United States",
    geometry: { type: "Point", coordinates: [-79.9311, 32.7765] },
  },
  {
    title: "Modern Apartment in Tokyo",
    location: "Tokyo",
    country: "Japan",
    geometry: { type: "Point", coordinates: [139.6503, 35.6762] },
  },
  {
    title: "Lakefront Cabin in New Hampshire",
    location: "New Hampshire",
    country: "United States",
    geometry: { type: "Point", coordinates: [-71.5724, 43.1939] },
  },
  {
    title: "Luxury Villa in the Maldives",
    location: "Maldives",
    country: "Maldives",
    geometry: { type: "Point", coordinates: [73.2207, 3.2028] },
  },
  {
    title: "Ski Chalet in Aspen",
    location: "Aspen",
    country: "United States",
    geometry: { type: "Point", coordinates: [-106.8175, 39.1911] },
  },
  {
    title: "Secluded Beach House in Costa Rica",
    location: "Costa Rica",
    country: "Costa Rica",
    geometry: { type: "Point", coordinates: [-83.7534, 9.7489] },
  },
];

module.exports = sampleListings;